app = "wilbot"
primary_region = "iad"

kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "node index.js"

[mounts]
  source = "wilbot_data"
  destination = "/app/data"
